version: "3"
services:
  mautic:
    restart: unless-stopped
    image: mautic/mautic
    depends_on:
      - mysql
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: ${MYSQL_MAUTIC_PASSWORD}
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
      MAUTIC_RUN_CRON_JOBS: "true"
    volumes:
      - mautic-web:/var/www/html

  mysql:
    restart: unless-stopped
    image: mysql:5.6
    #image: percona/percona-server:5.7
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: ${MYSQL_MAUTIC_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ssl-certs:/etc/ssl/private
      - ../../../nginx-certbot/data/certbot/conf:/etc/letsencrypt
    depends_on:
      - mautic
    entrypoint:
      - "bash"
      - "-c"
    command: |
      "exec nginx -g 'daemon off;'"

volumes:
  mautic-web:
  mysql:
  ssl-certs:
